[RF][ABC][navigation][submenu][y] Y_Submenu tests refactoring <AnastasiaYY>
RedRoverSchool/AutomationQA_05 pull request #273
Opened 2022-11-28 07:53 UTC by AnastasiaYY

refactor Y_Submenu tests to POM

[RF] - https://trello.com/c/XFDhNBH6/616-rfabcnavigationsubmenuy-ysubmenu-tests-refactoring-anastasiayy

2022-11-28 07:54 UTC, AnastasiaYY commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RF][ABC][navigation][submenu][y] Y_Submenu tests refactoring <AnastasiaYY>](https://trello.com/c/XFDhNBH6/616-rfabcnavigationsubmenuy-ysubmenu-tests-refactoring-anastasiayy)

2022-11-28 09:39 UTC, SafronovaOlga approved these changes

2022-11-28 19:10 UTC, ArinaJur requested changes

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    @FindBy(xpath = "//ul[@id = 'menu']//a[text() = 'Browse Languages']")
Лучше следовать стандартам проекта и искать меню по href.

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    private WebElement browseLanguages;
Измените, пожалуйста, название на browseLanguagesMenu

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +        click(browseLanguages);
Эта строка после изменения названий должна быть
click(browseLanguagesMenu);

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/pages/Y_SubmenuPage.java
> +public class Y_SubmenuPage extends AbcPage {
Переименуйте страницу на YPage пожалуйста

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/pages/Y_SubmenuPage.java
> +public class Y_SubmenuPage extends AbcPage {
И, скорее всего, она должна наследоваться от BrowseLanguagesSubmenu

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/tests/Y_SubmenuTest.java
> +public class Y_SubmenuTest extends BaseTest {
Название класса должно быть YTest

2022-11-28 19:10 UTC, ArinaJur commented on src/test/java/tests/Y_SubmenuTest.java
> +        for (String languageName : listYLanguages) {
ДЛя этого PR это не принципиально важно, но в будущем лучше эти вычисления сделать на странице YPage а здесь только вызвать метод для получения результата

2022-11-28 19:13 UTC, NataliiaOliver approved these changes

2022-11-28 19:26 UTC, AnastasiaYY commented
@ArinaJur Ирина, спасибо за замечания по моему PR, сейчас буду вносить изменения.

2022-11-28 19:49 UTC, AnastasiaYY commented on src/test/java/pages/Y_SubmenuPage.java
> +public class Y_SubmenuPage extends AbcPage {
@ArinaJur Ирина, поменяла здесь наследование от BrowseLanguagesSubmenu. До этого у меня некоторые методы и локаторы были в ABCpage,  а YPage наследовала от ABC. Сейчас после изменений мне нужно перенести эти методы и локаторы в BrowseLanguagesSubmenu?

2022-11-28 21:42 UTC, AnastasiaYY commented
@ArinaJur Ирина, исправила все кроме вычислений, которые вы посоветовали перенести на YPage. Это уже в следующий раз сделаю. пожалуйста, проверьте. Спасибо.

2022-11-29 03:05 UTC, ArinaJur requested changes
Осталось перенести на другую страницу только 1 элемент и 1 метод, а все остальное отлично!

2022-11-29 03:10 UTC, ArinaJur commented on src/test/java/pages/Y_SubmenuPage.java
> +public class Y_SubmenuPage extends AbcPage {
YPage не должна наследоваться от ABCPage. В вашем тесте вы с ABCPage вообще не работаете, вы на нее приземляетесь, но потом кликаете на ySubmenu из BrowseLanguagesSubmenuPage и сразу уходите на YPage. Языки вы должна считывать уже на YPage, сейчас у вас считывание языков на BrowseLanguagesSubmenuPage, а это неправильно, тк BrowseLanguagesSubmenuPage - это ТОЛЬКО кнопки Submenu. А таблица с названиями языков находится на YPage.

2022-11-29 04:30 UTC, AnastasiaYY commented on src/test/java/pages/Y_SubmenuPage.java
> +public class Y_SubmenuPage extends AbcPage {
спасибо за подробное разъяснение

2022-11-29 04:30 UTC, AnastasiaYY commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    @FindBy(xpath = "//table[@id = 'category']//a[starts-with(text(), 'Y')]")
перенесла

2022-11-29 04:30 UTC, AnastasiaYY commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    public List<String> getYLanguagesNames() {
перенесла

2022-11-29 04:31 UTC, verafes approved these changes

2022-11-29 04:31 UTC, AnastasiaYY commented
@ArinaJur Ирина, перенесла элемент и метод в YPage. Надеюсь все ))) Спасибо еще раз

2022-11-29 04:37 UTC, ArinaJur approved these changes
Все )))). ОТличная работа!

2022-11-29 04:42 UTC, merged