[RF][Start][navigation][submenu][lyrics]testSongLyricsSubmenu() <AnzhelikaBaa>
RedRoverSchool/AutomationQA_05 pull request #286
Opened 2022-11-30 13:09 UTC by AnzhelikaBaa

testSongLyricsSubmenu() refactored.
[RF][Start][navigation][submenu][lyrics] - https://trello.com/c/ubXu0XBg/633-rfstartnavigationsubmenulyricstestsonglyricssubmenu-anzhelikabaa

2022-11-30 20:15 UTC, SergeiKuznetsov commented on src/test/java/tests/LyricsTest.java
> -}
Может лучше вообще удалить этот класс?

2022-11-30 20:17 UTC, SergeiKuznetsov commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +
```suggestion

    @Test
    public void testSongLyricsSubmenu() {
        final String expectedSubmenuSongLyricsTitle = "Song Lyrics";
        final String expectedURL = "https://www.99-bottles-of-beer.net/lyrics.html";

        SongLyricsSubmenuPage songLyricsSubmenuPage = openBaseURL().clickSongLyricsSubmenuPage();

        String actualSubmenuSongLyricsTitle = songLyricsSubmenuPage.getSongLyricsSubmenuLabelText();

        String actualURL = songLyricsSubmenuPage. getExternalPageURL();

        Assert.assertEquals(actualSubmenuSongLyricsTitle, expectedSubmenuSongLyricsTitle);
        Assert.assertEquals(actualURL, expectedURL);
    }
}
```

2022-11-30 21:33 UTC, AnzhelikaBaa commented on src/test/java/tests/LyricsTest.java
> -}
I didn't create this class. I assume it was made for Lyrics Page. My test is for the submenu.

2022-11-30 22:29 UTC, elviraKh1 commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        SongLyricsSubmenuPage songLyricsSubmenuPage = openBaseURL().clickSongLyricsSubmenuPage();
кажется я была сегодня не права, когда посоветовала вам создать переменную SongLyricsSubmenuPage songLyricsSubmenuPage...  кажется вся концепция создания этого класса лишняя и вам надо было использовать изначально LyricsPage

2022-11-30 22:55 UTC, SergeiKuznetsov commented on src/test/java/tests/LyricsTest.java
> -}
В вашем запросе вы добавляете несколько пробелов в этот класс. Зачем?
Либо не изменяйте этот класс, либо удалите.

2022-11-30 22:58 UTC, SergeiKuznetsov commented on src/test/java/tests/LyricsTest.java
> -}
Сделайте Rollback в IntelliJ либо сделайте тут Restore 
![image](https://user-images.githubusercontent.com/13728212/204926051-f683ce50-e52c-45c3-a118-873d6f5c923c.png)

2022-11-30 23:17 UTC, AnzhelikaBaa commented on src/test/java/tests/LyricsTest.java
> -}
> В вашем запросе вы добавляете несколько пробелов в этот класс. Зачем? Либо вообще не трогайте класс, либо удалите.

I am not sure what spaces you refer to. Would you specify?

2022-11-30 23:25 UTC, AnzhelikaBaa commented on src/test/java/tests/LyricsTest.java
> -}
> В вашем запросе вы добавляете несколько пробелов в этот класс. Зачем? Либо вообще не трогайте класс, либо удалите.

My first intention was to use this class, but later I changed my mind. Maybe I did changes by mistake.

2022-12-01 01:13 UTC, ArinaJur requested changes

2022-12-01 01:13 UTC, ArinaJur commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +public class SubMenuSongLyricsTest extends BaseTest {
Наверное, вы хотели протестировать текст на кнопке Song Lyrics и Url страницы? Это должны быть 2 разных теста. 
Один на текст кнопки - в этом случае не нужно кликать на эту кнопку, а только считать текст
Один на URL страницы - тогда нужно кликнуть на кнопку и считать url
Оба теста должны находиться на странице StartSubmenuTest

2022-12-01 01:13 UTC, ArinaJur commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        final String expectedSubmenuSongLyricsTitle = "Song Lyrics";
Эта переменная не считывает title (title - это внутренее название страницы, которое мы не видим глазами, только в коде
А вы тестируете текст на кнопке, потому переменная должна быть expectedSongLyricsSubmenuText

2022-12-01 01:13 UTC, ArinaJur commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +    public void testSongLyricsSubmenu() {
testSongLyricsSubmenuText

2022-12-01 01:13 UTC, ArinaJur commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        final String expectedURL = "https://www.99-bottles-of-beer.net/lyrics.html";
Это должно быть вынесено в отдельный тест testSongLyricsSubmenuNavigatesToSongLyricsPage

2022-12-01 01:13 UTC, ArinaJur commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        SongLyricsSubmenuPage songLyricsSubmenuPage = openBaseURL().clickSongLyricsSubmenuPage();
Шаги для тестирования Текста кнопки должны быть 
String songLyricsSubmenuText = openBaseUrl()
. getSongLyricsSubmenuText();
.

2022-12-01 01:13 UTC, ArinaJur commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        String actualURL = songLyricsSubmenuPage. getExternalPageURL();
Нкжно разнести это на 2 теста. Пока исправьте замечания выше, а потом посмотрим, что с тестами

2022-12-01 01:49 UTC, elviraKh1 commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        final String expectedSubmenuSongLyricsTitle = "Song Lyrics";
мы видим title - это название вкладки в браузере

2022-12-01 02:24 UTC, AnzhelikaBaa commented on src/test/java/tests/SubMenuSongLyricsTest.java
> +        String actualURL = songLyricsSubmenuPage. getExternalPageURL();
Should I do two separate tests in StartSubmenuTest ?

2022-12-01 03:07 UTC, SergeiKuznetsov approved these changes

2022-12-01 18:59 UTC, closed without merging