[RF][POM][Structure][AbcPage] [submenu][team] Refactoring pages, methods, locators <katy1313>
RedRoverSchool/AutomationQA_05 pull request #288
Opened 2022-11-30 15:32 UTC by katy1313

POM created, 3 tests refactored using POM
[RF] - https://trello.com/c/oBD3Y0L7/635-rfpomstructureabcpage-submenuteam-refactoring-pages-methods-locators-katy1313

2022-12-01 01:55 UTC, ArinaJur requested changes

2022-12-01 01:55 UTC, ArinaJur commented on src/test/java/old_tests/Katy1313Test.java
> +        return driver.findElement(by);
в этой строке лишний пробел в начале. Уберите его, пожалуйста, его не надо было добавлять

2022-12-01 01:55 UTC, ArinaJur commented on src/test/java/old_tests/Katy1313Test.java
> +    @Test
Уберите, пожалуйста все лишние пробелы в начале каждой строки, сделав Code -> Reformat code

2022-12-01 01:55 UTC, ArinaJur commented on src/test/java/pages/ABCPage.java
> +    private WebElement h2Category;
Этот элемемнт нужно назвать  h2Header, тк по коду это Header

2022-12-01 01:55 UTC, ArinaJur commented on src/test/java/tests/PTest.java
> +        List<String> displayed = new ArrayList<String>();
displayedLanguages

2022-12-01 01:55 UTC, ArinaJur commented on src/test/java/tests/PTest.java
> +        List<String> sorted = new ArrayList<String>();
sortedLanguages

2022-12-01 01:55 UTC, ArinaJur commented on src/test/java/tests/PTest.java
> +        Assert.assertEquals(displayed, sorted);
Этот тест очень хороший и на правильной странице!

2022-12-01 15:22 UTC, katy1313 commented on src/test/java/tests/PTest.java
> +        Assert.assertEquals(displayed, sorted);
Ирина, спасибо большое! Я все исправила. Проверьте пожалуйста. Мне нужно переделывать карточку Trello согласно изменениям или сделать новую?

2022-12-02 09:27 UTC, ArinaJur approved these changes
Отлично! Получилось очень аккуратно и красиво!

2022-12-02 09:28 UTC, ArinaJur commented on src/test/java/tests/PTest.java
> +        Assert.assertEquals(displayed, sorted);
Нет, карточку не нужно переделывать. )

2022-12-02 09:34 UTC, VasiliySiniavin approved these changes

2022-12-02 09:34 UTC, linavolovick approved these changes

2022-12-02 09:37 UTC, merged

2022-12-02 14:08 UTC, katy1313 commented
> Отлично! Получилось очень аккуратно и красиво!

Ура! спасибо большое!