[RF][Submitnewlanguage][main][header][h2]test_VerifyHeaderText_POM<ElenaKud>
RedRoverSchool/AutomationQA_05 pull request #289
Opened 2022-11-30 18:29 UTC by elenaK-2018

RFtestVerifyH2HeaderTest_SubmitNewLanguage()_POM
[RF]-https://trello.com/c/o6OhBN2R/632-rfsubmitnewlanguagemainheaderh2testverifyheadertextpomelenakud

2022-11-30 23:28 UTC, SergeiKuznetsov approved these changes

2022-12-01 01:59 UTC, ArinaJur requested changes
Хороший тест, только название нужно исправить

2022-12-01 01:59 UTC, ArinaJur commented on src/test/java/tests/SubmitNewLanguageTest.java
> +    public void testVerifyH2HeaderTest_SubmitNewLanguage() {
Лучше назвать testH2Header - мы не пишем слово Verify в названии автотестов, и мы итак находимя на SubmitNewLanguageTest, это дублированная информация в названии

2022-12-01 02:12 UTC, ArinaJur commented on src/test/java/pages/SubmitNewLanguagePage.java
> +    public String getTextH2Header() {
getH2HeaderText()

2022-12-01 05:49 UTC, elenaK-2018 commented on src/test/java/tests/SubmitNewLanguageTest.java
> +    public void testVerifyH2HeaderTest_SubmitNewLanguage() {
Спасибо, исправлю)

2022-12-01 06:31 UTC, elenaK-2018 commented on src/test/java/pages/SubmitNewLanguagePage.java
> +    public String getTextH2Header() {
Ок, исправлю, спасибо!

2022-12-02 09:40 UTC, ArinaJur approved these changes
Хорошо!

2022-12-02 09:47 UTC, merged