[RF][POM][Main][header][h1][h2] Verify headers on start page <MariyaSvetlova>
RedRoverSchool/AutomationQA_05 pull request #290
Opened 2022-11-30 20:23 UTC by lmt3103

Rf main headers h1 h2 pom verify header on start page POM

[RF] - https://trello.com/c/EBjDuTWP/637-rfpommainheaderh1h2-verify-headers-on-start-page-mariyasvetlova

2022-11-30 23:28 UTC, SergeiKuznetsov approved these changes

2022-12-01 02:11 UTC, ArinaJur requested changes

2022-12-01 02:11 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    public String getTextHeaderH2() {
getH2HeaderText()

2022-12-01 02:11 UTC, ArinaJur commented on src/test/java/tests/HeadersTest.java
> +    public void testHeaderH1OnStartPage() {
testH1Header()   - он находится не только на StartPage, его видно с абсолютно любой страницы

2022-12-01 02:11 UTC, ArinaJur commented on src/test/java/tests/HeadersTest.java
> +        final String HEADER_H1_TEXT = "99 Bottles of Beer";
EXPECTED_H1_HEADER

2022-12-01 02:11 UTC, ArinaJur commented on src/test/java/tests/HeadersTest.java
> +    public void testHeaderH2OnStartPage() {
Этот тест тоже должен быть на странице MainTest

2022-12-01 02:11 UTC, ArinaJur commented on src/test/java/tests/HeadersTest.java
> +        Assert.assertEquals(openBaseURL().getTextHeaderH2(),HEADER_H2_TEXT);
То же самое - вынесите действия за ассерт. Мы так никогда не писали, мы всегда учились писать по ААА паттерн

2022-12-01 09:22 UTC, lmt3103 commented on src/test/java/tests/HeadersTest.java
> +        Assert.assertEquals(openBaseURL().getTextHeaderH2(),HEADER_H2_TEXT);
Большое Вам спасибо за все замечания и подробные комментарии, все сразу стало понятнее!!!!!

2022-12-01 10:07 UTC, lmt3103 commented
Ошибки исправлены

2022-12-02 09:50 UTC, ArinaJur approved these changes
ОТлично!

2022-12-02 10:01 UTC, merged