[RF][POM][Structure][Lyrics][main][header][text] Refactoring pages, methods, locators<EkaterinaKochelorova>
RedRoverSchool/AutomationQA_05 pull request #291
Opened 2022-11-30 21:24 UTC by EkaterinaKochelorova

POM Refactoring StartSubmenuPage, LyricsPage, methods and locators, 2 tests refactored using POM
[RF] - https://trello.com/c/hDm2VcHC/636-rfpomstructurelyricsmainheadertext-refactoring-pages-methods-locatorsekaterinakochelorova

2022-11-30 23:24 UTC, SergeiKuznetsov approved these changes

2022-12-01 02:27 UTC, ArinaJur requested changes

2022-12-01 19:58 UTC, EkaterinaKochelorova commented on src/test/java/tests/StartSubmenuLyricsTest.java
> +    public void testPTagText_WhenChooseSubmenuLyrics() {
Все замечания исправила

2022-12-02 10:03 UTC, ArinaJur approved these changes

2022-12-02 10:23 UTC, merged