[RF][POM][Main][Top Lists menu]testVerifyListOfElementsOfTopListsMenu()<Albina-star>
RedRoverSchool/AutomationQA_05 pull request #292
Opened 2022-11-30 23:00 UTC by Albina-star

[RF] - https://trello.com/c/bwqnP4zB/639-rfpommaintop-lists-menutestverifylistofelementsoftoplistsmenualbina-star

2022-11-30 23:23 UTC, SergeiKuznetsov approved these changes

2022-12-01 02:42 UTC, ArinaJur requested changes
тест хороший, но надо перенести на правильную страницу  и исправить несколько неточностей

2022-12-01 02:42 UTC, ArinaJur commented on src/test/java/pages/TopListsSubmenuPage.java
> +    private List<WebElement> topListSubmenuList;
Наверное, это лучше назвать topListsSubmenus, а то 2 слова List в одном названии )

2022-12-01 02:42 UTC, ArinaJur commented on src/test/java/pages/TopListsSubmenuPage.java
> +    public List<String> getText() {
А здесь можно кастомизировать - getSubmenusTexts()

2022-12-01 02:42 UTC, ArinaJur commented on src/test/java/tests/TopListsTest.java
> +    public void testVerifyListOfElementsOfTopListsMenu() {
Мы не пишем Verify в названии автотестов и в жданном тесте вы не элементу проверяете, а названия сабменюшек. Лучше назвать testTopListsSubmenuTexts()

2022-12-01 02:42 UTC, ArinaJur commented on src/test/java/tests/TopListsTest.java
> +    public void testVerifyListOfElementsOfTopListsMenu() {
И этот тест должен быть на страницеTopListsSubmenuTest
Тк мы тестируем только тект на сабменю и ничего не тестируем на странице Top Lists

2022-12-01 02:42 UTC, ArinaJur commented on src/test/java/tests/TopListsTest.java
> +        List<String> expectedElementsOfTopListsMenu = new ArrayList<>();
expectedSubmenuTexts

2022-12-01 02:42 UTC, ArinaJur commented on src/test/java/tests/TopListsTest.java
> +        List<String> actualElementsOfTopListsMenu =
ActualSubmenuTexts - вас же тексты List<String>, а не элементы List<WebElement>

2022-12-01 03:48 UTC, Albina-star commented
> тест хороший, но надо перенести на правильную страницу и исправить несколько неточностей

Все исправления внесла.  Ирина, спасибо большое за подробное ревью, показали ошибки, которые я и не видела.

2022-12-02 10:09 UTC, ArinaJur approved these changes
Хорошая работа проделана!

2022-12-02 10:20 UTC, merged