[RF][B][main][header][h2] testHeaderH2Text_WhenOpenBrowseLanguageMenu_PageBSubmenu() <Nstzya>
RedRoverSchool/AutomationQA_05 pull request #293
Opened 2022-11-30 23:34 UTC by nstzya

testHeaderH2Text_WhenOpenBrowseLanguageMenu_BSubmenu() refactored, old test ignored

[RF] - https://trello.com/c/HMNAi2KO/638-rfbmainheaderh2-testheaderh2textwhenopenbrowselanguagemenupagebsubmenu-nstzya

2022-12-01 02:50 UTC, ArinaJur requested changes

2022-12-01 02:50 UTC, ArinaJur commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    private WebElement headerH2BSubmenu;
Этот элемент должен быть на странице BPage и называться h2Header

2022-12-01 02:50 UTC, ArinaJur commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    public String getHeaderH2BSubmenuText() {
Этот метод должен быть на странице BPage
getH2Header()

2022-12-01 02:50 UTC, ArinaJur commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +    @Test
Этот тест должен быть на странице BPage, тк вы делаете ассерты с самой страницы, а не проверяете названия сабменю

2022-12-01 04:01 UTC, nstzya commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    private WebElement headerH2BSubmenu;
this change applied

2022-12-01 04:01 UTC, nstzya commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    public String getHeaderH2BSubmenuText() {
this change applied

2022-12-01 04:01 UTC, nstzya commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +    @Test
this change applied

2022-12-01 04:01 UTC, nstzya commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +    public void testHeaderH2Text_WhenOpenBrowseLanguageMenu_BSubmenu() {
this change applied

2022-12-02 10:25 UTC, ArinaJur approved these changes
Все хорошо!

2022-12-02 10:33 UTC, merged