[RF][POM][Main][navigation][menu][toplist] testTheMostRatedRealLanguageIsDifferFromMostRatedEsotericLanguage_ekaterinalizina
RedRoverSchool/AutomationQA_05 pull request #295
Opened 2022-12-01 03:04 UTC by ekaterinalizina

[RF][POM] - https://trello.com/c/lKFdFldp/641-rf-pr-name-github-username

2022-12-01 04:44 UTC, NataliiaOliver submitted a review, later dismissed
LGTM

2022-12-01 20:32 UTC, Yuliya-14 approved these changes

2022-12-02 02:53 UTC, ekaterinalizina commented
@NataliiaOliver спасибо большое за комментарий, убрала Verify, не знаю как сделать короче название ветки или теста без потеря смысла

2022-12-02 11:37 UTC, ArinaJur reviewed
Помечу здесь, позже вернусь

2022-12-02 11:37 UTC, ArinaJur commented on src/test/java/pages/BasePage.java
> +    public String getFirstTextFromElementsListToLowerCase(List<WebElement> elementList){
Как ни хотелось пропустить, но давайте, все же, подправим PR, тк в нем важные методы. 
FirstText -  вы имеете в виду что мы берем первый элемент из списка и считываем с него текст? ИЛи что для каждого элемента может быть много текстов, но мы берем только первый?

Если первый вариант, то давайте назовем getFirstElementTextInLowerCase(), а если второй вариант, то давайте назовем getFirstTextForEachElementInLowerCase()

2022-12-02 11:37 UTC, ArinaJur commented on src/test/java/pages/BasePage.java
> +        getListTextInLowerCase(elementList);
Здесь нужно написать 
List<String> texts = getListTextInLowerCase(elementList);

А то так, как написано сейчас, вы считываете эти тексты 4 раза, тк 4 раза вызываете метод. Но мы вызовем  метод 1 раз и сразу сохраним результат, чтобы использовать позже

2022-12-02 11:37 UTC, ArinaJur commented on src/test/java/pages/BasePage.java
> +        if(getListTextInLowerCase(elementList).size() > 0){
ТОгда здесь надо написать
```
if(texts.size() > 0){

return texts.get(0);
}

return "";
```

2022-12-02 11:37 UTC, ArinaJur commented on src/test/java/pages/BasePage.java
> +    public String getFirstTextFromElementsListToUpperCase(List<WebElement> elementList){
И этот метод по тому же принципу

2022-12-02 13:21 UTC, ArinaJur requested changes

2022-12-02 13:21 UTC, ArinaJur commented on src/test/java/pages/TopListEsotericPage.java
> +    public String getFirstTextFromTopRatedEsotericListToLowerCase() {
Здесь лучше тоже кастомизировать - getMostRatedEsotericLanguage() { -  здесь нам уже не важно, что в нижнем регистре, тк это шаг теста, а не техническая подробность

2022-12-02 13:21 UTC, ArinaJur commented on src/test/java/pages/TopListRealPage.java
> +    public String getFirstTextFromTopRatedRealListToLowerCase() {
getMostRatedRealLanguage()

2022-12-02 13:21 UTC, ArinaJur commented on src/test/java/pages/TopListsSubmenuPage.java
> +    public TopListRealPage clickTopRatedRealSubmenuMenu() {
clickTopRatedRealSubmenu()

2022-12-02 13:21 UTC, ArinaJur commented on src/test/java/pages/TopListsSubmenuPage.java
> +    public TopListEsotericPage clickTopRatedEsotericSubmenuMenu() {
lickTopRatedEsotericSubmenu()

2022-12-02 13:21 UTC, ArinaJur commented on src/test/java/tests/TopListEsotericTest.java
> +        String topRatedRealLanguagesFirstLanguage = openBaseURL()
Мы не используем слово Verify в названии автотеста, у нас уже есть test -  это аналог verify
testTheMostRatedRealLanguageIsDifferFromMostRatedEsotericLanguage()

2022-12-02 13:21 UTC, ArinaJur commented on src/test/java/tests/TopListEsotericTest.java
> +        String topRatedEsotericLanguagesFirstLanguage = openBaseURL()
В середине теста мы можем не открывать заново baseURL, а просто можно создать 

TopListEsotericPage topListEsotericPage = new TopListEsotericPage();

String theMostRatedEsotericLanguage = topListEsotericPage.clickTopRatedEsotericSubmenuMenu()
                .getFirstTextFromTopRatedEsotericListToLowerCase();

2022-12-02 16:55 UTC, ekaterinalizina commented on src/test/java/tests/TopListEsotericTest.java
> +        String topRatedEsotericLanguagesFirstLanguage = openBaseURL()
@ArinaJur cпасибо Вам огромное за комментарии и кропотливый труд все проверить, смогу заняться исправлением только через 6 ч, так как на работе.

2022-12-03 01:10 UTC, ekaterinalizina commented on src/test/java/tests/TopListEsotericTest.java
> +        String topRatedEsotericLanguagesFirstLanguage = openBaseURL()
@ArinaJur , посмотрите, пожалуйста, при возможности,  все изменения внесла

2022-12-03 02:27 UTC, ArinaJur approved these changes

2022-12-03 02:27 UTC, merged