[RF][ABC][navigation][submenu][zero] testVerifyTextAndLink()<AleksandrAkimovChg>
RedRoverSchool/AutomationQA_05 pull request #299
Opened 2022-12-01 17:48 UTC by AleksandrAkimovChg

testVerifyTextAndLink() refacrored to POM model

[RF] - https://trello.com/c/mpu2fULc/647-rfabcnavigationsubmenuzero-testverifytextandlinkaleksandrakimovchg

2022-12-01 17:57 UTC, AleksandrAkimovChg commented
![image](https://user-images.githubusercontent.com/104619642/205125755-e5093bdc-6bc8-424c-b041-12cfc2aa8805.png)
по идее еще должен проверить Navigation, но тогда я уйду на другую страницу, что не ложится в POM model (непонятно...)

2022-12-02 05:22 UTC, AleksandrAkimovChg commented
от этой ветки создан новый PR - https://github.com/RedRoverSchool/AutomationQA_05/pull/307

2022-12-02 10:35 UTC, SafronovaOlga approved these changes

2022-12-02 15:02 UTC, ArinaJur requested changes

2022-12-02 15:02 UTC, ArinaJur commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +        Assert.assertTrue(
Мы на проекте не вносим действия в Assert, мы учимся писать тесты по AAA паттерн. Те все действия - act - отдельно. и получаем actual result, а все асссерты отдельно - assert. Вынесите, пожалуйста, действия из ассертов

2022-12-02 15:02 UTC, ArinaJur commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +        Assert.assertEquals(
И здесь тоже выносим действия из Asserts

2022-12-02 15:30 UTC, ArinaJur commented
> ![image](https://user-images.githubusercontent.com/104619642/205125755-e5093bdc-6bc8-424c-b041-12cfc2aa8805.png) по идее еще должен проверить Navigation, но тогда я уйду на другую страницу, что не ложится в POM model (непонятно...)

++++++++++++++++++++++++

Когда мы проверяем навигацию, мы не уходим на другую страницу. Мы прямо с этой страницы вызываем метод getTitle и  get URL и
1 Подтверждаем, что они - не те же самые, какие были до того, что доказывает , что навигация случилась
2ю Они именно те, как мы ожидали, что доказывает, что навигация правильная.
И все )

2022-12-02 15:42 UTC, AleksandrAkimovChg commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    private List<WebElement> symbolInSubmenu;
поправил

2022-12-02 15:44 UTC, AleksandrAkimovChg commented on src/test/java/pages/BrowseLanguagesSubmenuPage.java
> +    public String getLinkBySymbol(String symbol) {
Ок, исправлю отдельным тикетом и наверное в TestUtils

2022-12-02 16:32 UTC, AleksandrAkimovChg commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +        Assert.assertTrue(
Вынес в булевое значение, но раньше такого не видел, поэтому возможно, что первый асерт прописал некорректно Скажите, так корретно прописать асерт?
-----
Boolean actualResultTrue...
 Assert.assertTrue(actualResultTrue);

2022-12-02 16:58 UTC, AleksandrAkimovChg commented
> 



> > ![image](https://user-images.githubusercontent.com/104619642/205125755-e5093bdc-6bc8-424c-b041-12cfc2aa8805.png) по идее еще должен проверить Navigation, но тогда я уйду на другую страницу, что не ложится в POM model (непонятно...)
> 
> ++++++++++++++++++++++++
> 
> Когда мы проверяем навигацию, мы не уходим на другую страницу. Мы прямо с этой страницы вызываем метод getTitle и get URL и 1 Подтверждаем, что они - не те же самые, какие были до того, что доказывает , что навигация случилась 2ю Они именно те, как мы ожидали, что доказывает, что навигация правильная. И все )

-----
Извиняюсь за дотошность, но я делал проверку по сабменю опираясь на матрицу
![image](https://user-images.githubusercontent.com/104619642/205344506-1be0d051-93bc-4de4-b9e1-2decdcf2991a.png)
Получается тогда надо деать отдельный тест (не в рамках символа) на проверку https://www.99-bottles-of-beer.net/abc.html и его Title?

2022-12-03 02:31 UTC, ArinaJur approved these changes

2022-12-03 02:36 UTC, ArinaJur commented on src/test/java/tests/BrowseLanguagesSubmenuTest.java
> +        Assert.assertTrue(
Правильно примерно так, но мы еще этот тест отрефакторим и завтра как раз будем писать разные виды тестов
                BrowseLanguage browseLanguage = openBaseURL()
                .clickBrowseLanguagesMenu()
                .getListSymbolsInSubmenu();


        Assert.assertTrue(browseLanguage.contains(symbol););

2022-12-03 02:37 UTC, ArinaJur commented
> Извиняюсь за дотошность, но я делал проверку по сабменю опираясь на матрицу ![image](https://user-images.githubusercontent.com/104619642/205344506-1be0d051-93bc-4de4-b9e1-2decdcf2991a.png) Получается тогда надо делать отдельный тест (не в рамках символа) на проверку https://www.99-bottles-of-beer.net/abc.html и его Title?

Да )

2022-12-03 02:38 UTC, merged