[RF][Structure][Project][POM]Creating multiple POM classes, locators and methods for ABC Page and GuestBookv2 Page <AramH20>
RedRoverSchool/AutomationQA_05 pull request #303
Opened 2022-12-01 20:01 UTC by AramH20

refactoring test_ABCVerifyByLetterCategoryInformation() andtest_MainFooterGuestBookv2_AramH20() by POM

[RF]- https://trello.com/c/bEAXZEUh/653-rfstructureprojectpomcreating-multiple-pom-classes-locators-and-methods-for-abc-page-and-guestbookv2-page-aramh20

[AT] - https://trello.com/c/qoTxbBao/655-atstructureprojectpomcreating-multiple-pom-classes-locators-and-methods-for-abc-page-and-guestbookv2-page-aramh20

[US] - https://trello.com/c/it1u3DQj/654-usstructureprojectpomcreating-multiple-pom-classes-locators-and-methods-for-abc-page-and-guestbookv2-page-aramh20

2022-12-03 04:11 UTC, ArinaJur requested changes

2022-12-03 04:11 UTC, ArinaJur commented on src/test/java/pages/TablePage.java
> +    public List<String> getColumLanguageList(WebElement element){
getLaguagesColumnList

2022-12-03 04:11 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +        List<WebElement> submenuLetters =
lettersSubmenus

2022-12-03 04:11 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +        List<String> culumlanguagesNames =
columnWithLanguagesNames

2022-12-03 04:11 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +                    openBaseURL()
Эти действия в цикле for будут много раз начинать тест с открытия страницы. Лучше действия теста не вносить внутрь цикла for

Сначала сохраните список

List<String> languages =
                    openBaseURL()
                            .clickBrowseLanguagesMenu()
                            .getColumnLanguageList(submenuLetters.get(i));
                            
                            А потом напишите цикл for и обращайтесь к сохраненному списку
                            
                           for (String language : languages) {
                Assert.assertEquals(String.valueOf(language.charAt(0)), culumlanguagesNames.get(i));
            }

2022-12-03 04:11 UTC, ArinaJur commented
Нужно просто изменить структуру теста

2022-12-03 07:33 UTC, AramH20 commented on src/test/java/tests/ABCTest.java
> +                    openBaseURL()
я знаю, что двойные циклы нехорошо, но здесь надо нажать на соответствующую букву и потому создать список List<String> languages. Уникс у всех одинаковый спатх, я несмог както их розделит. поэтому я пропосал метод getColumnLanguageList(submenuLetters.get(i))  с параметром WebElement. Пока не нахожу вариант лучше и уже поздно что то м ержит у вас урок скоро. После завтрашнего урока попробую улучшить. Если мое кот мешает просто закроете его я новый ПР зделаю . А по поводу прописи название классов и методов к учету. 
Огромное с посибо Ирина  )))

2022-12-05 03:03 UTC, ArinaJur commented on src/test/java/pages/ABCPage.java
> +    public ABCPage clickBrowseLanguagesSubmenuLetter(int i) throws InterruptedException {
Я убрала )

2022-12-05 03:06 UTC, ArinaJur commented on src/test/java/pages/base_abstract/MainPage.java
> +    public GuestBookV2Page clickGuestbookMenu() {
Исправила

2022-12-05 03:06 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +                    openBaseURL()
я имела в виду, что чтобы прокликать на кнопки, не нужно каждый раз заново открывать сайт в новом окне, а метод openBaseURL() именно это и делает )

2022-12-05 03:08 UTC, ArinaJur approved these changes

2022-12-05 03:09 UTC, IrynaHryhoriv approved these changes

2022-12-05 03:09 UTC, merged