set static final String BASE_URL
RedRoverSchool/AutomationQA_05 pull request #31
Opened 2022-11-13 13:14 UTC by mbatoz

verifyWishesFromTheTeamTest added

2022-11-13 13:53 UTC, SafronovaOlga approved these changes

2022-11-13 14:45 UTC, ArinaJur requested changes
Пожалуйста, добавьте в описание ссылки на карточки Trello  и оформите правильно заголовок PR

2022-11-14 18:59 UTC, ArinaJur commented
Нужно пойти на Трелло, найти ваши карточки для PR, скопировать ссылки и поставить в описание PR. Как в этом PR
![Screenshot_20221114_135832_Chrome](https://user-images.githubusercontent.com/66705803/201743361-7013753b-7577-4e1b-8020-65037aa09eeb.png)

2022-11-17 15:06 UTC, ArinaJur commented
Если вам нужна помощь с этим PR,  напишите в личку

2022-11-19 14:48 UTC, ArinaJur approved these changes

2022-11-19 14:50 UTC, merged