[RF][POM][Z][main][text]testNamesOfLanguagesOnPageZStartWithZ() <AnzhelikaBaa>
RedRoverSchool/AutomationQA_05 pull request #313
Opened 2022-12-02 16:48 UTC by AnzhelikaBaa

RFPOMZMainText_testNamesOfLanguagesOnPageZStartWithZ() refactored

[RF][POM][Z][main][text]testNamesOfLanguagesOnPageZStartWithZ() - https://trello.com/c/p6qDkb6I/659-rfpomzmaintexttestnamesoflanguagesonpagezstartwithz-anzhelikabaa

2022-12-03 05:21 UTC, ArinaJur requested changes

2022-12-03 05:21 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +        public String getSongLyricsSubmenuText () {
В этом PR съехал весь код, сделайте Code -> Reformat code, пожалуйста

2022-12-05 00:27 UTC, AnzhelikaBaa commented on src/test/java/pages/MainPage.java
> +        public String getSongLyricsSubmenuText () {
The code is reformatted.

2022-12-05 03:42 UTC, ArinaJur approved these changes

2022-12-05 03:42 UTC, ArinaJur commented on src/test/java/pages/browse_languages/BrowseLanguagesSubmenuPage.java
> +    }
Я этот локатор и метод перенесла в 
BrowseLanguagesSubmenuPage
Если вы работаете с сабменю, то смотрите к какому главному меню они относятся, и переносите локаторы и клин на страницу сабменю для этого меню

2022-12-05 03:42 UTC, ArinaJur commented on src/test/java/pages/browse_languages/letters/ZPage.java
> +        return getListTextInLowerCase(zList);
Этот локатор и метод есть в TablePage в универсальном виде. Пока оставим, как есть, тк тесты еще будут рефактоиться. НО для будущих тестов используйте методы страницы Table

2022-12-05 03:43 UTC, merged