[RF][Impressum][main][text] testTextEmailAdressOnThePage() <Enmedv>
RedRoverSchool/AutomationQA_05 pull request #319
Opened 2022-12-02 21:09 UTC by enmedv

testTextOnThePageImpressum created in POM, locators and methods added

[RF] - https://trello.com/c/GNbEOc8v/665-rfimpressummaintext-testtextemailadressonthepage-enmedv

2022-12-04 09:45 UTC, SafronovaOlga approved these changes

2022-12-05 03:37 UTC, ArinaJur requested changes

2022-12-05 03:37 UTC, ArinaJur commented on src/test/java/pages/start/PrivacyPage.java
> +    private WebElement textEmailAdressOnThePage;
Исправьте на emailAddress, пожалуйста

2022-12-05 03:37 UTC, ArinaJur commented on src/test/java/pages/start/PrivacyPage.java
> +    public String getTextEmailAddressOnThePage() {
getEmailAddress()

2022-12-05 21:20 UTC, enmedv commented on src/test/java/pages/start/PrivacyPage.java
> +    private WebElement textEmailAdressOnThePage;
Здравствуйте. Спасибо за рекомендации. Исправила.

2022-12-05 21:20 UTC, enmedv commented on src/test/java/pages/start/PrivacyPage.java
> +    public String getTextEmailAddressOnThePage() {
Здравствуйте. Спасибо за рекомендации. Исправила.

2022-12-05 21:20 UTC, enmedv commented on src/test/java/tests/PrivacyTest.java
> +        String expectedTextEmailAddressOnThePage = "os@ls-la.net";
Здравствуйте. Спасибо за рекомендации. Исправила.

2022-12-07 05:09 UTC, verafes approved these changes

2022-12-08 17:38 UTC, ArinaJur approved these changes
Отлично!

2022-12-08 17:38 UTC, merged