[RF][POM][Start][Main][Text] VerifyWishesFromTheTeam <ElenaStrat>
RedRoverSchool/AutomationQA_05 pull request #325
Opened 2022-12-03 11:20 UTC by ElenaStrat

1.testWishesFromTheTeamFirstParagraph was refactored and added to POM
2.method getTeamWishes was added in StartPage.java

[RF] - https://trello.com/c/CFMAYrvq/670-rfpomstartmaintext-verifywishesfromtheteam-elenastrat

2022-12-03 14:05 UTC, SafronovaOlga approved these changes

2022-12-05 05:27 UTC, ArinaJur requested changes

2022-12-05 05:27 UTC, ArinaJur commented on src/test/java/pages/start/StartPage.java
> +    private WebElement verifyText;
этот локатор находит все 5 параграфов - "<p>"
Если вам нужен только первый параграф, используйте 
By.xpath("//div[@id = 'main']/p[1]"

2022-12-05 05:27 UTC, ArinaJur commented on src/test/java/tests/StartTest.java
> +        String TeamWishes = openBaseURL()
Переменные называем с маленькой буквы

2022-12-05 14:48 UTC, closed without merging