[RF][Structure][Project][POM]Creating multiple POM classes, updated  test_ABCLetterCategoryLanguagesColumInformation() test <AramH20>
RedRoverSchool/AutomationQA_05 pull request #344
Opened 2022-12-06 09:00 UTC by AramH20

updated test_ABCLetterCategoryLanguagesColumInformation() test

[RF]- https://trello.com/c/bEAXZEUh/653-rfstructureprojectpomcreating-multiple-pom-classes-locators-and-methods-for-abc-page-and-guestbookv2-page-aramh20

[AT] - https://trello.com/c/qoTxbBao/655-atstructureprojectpomcreating-multiple-pom-classes-locators-and-methods-for-abc-page-and-guestbookv2-page-aramh20

[US] - https://trello.com/c/it1u3DQj/654-usstructureprojectpomcreating-multiple-pom-classes-locators-and-methods-for-abc-page-and-guestbookv2-page-aramh20

2022-12-06 19:12 UTC, SergeiKuznetsov commented on src/test/java/pages/base_abstract/TablePage.java
> +//        return getListTextInLowerCase(letters);
```suggestion
```

2022-12-06 19:12 UTC, SergeiKuznetsov commented on src/test/java/pages/base_abstract/TablePage.java
>      }
```suggestion
    }

```

2022-12-06 19:13 UTC, SergeiKuznetsov commented on src/test/java/tests/ABCTest.java
> +        for(int i = 1; i < expectedLanguagesNames.size(); i++) {
```suggestion
        for (int i = 1; i < expectedLanguagesNames.size(); i++) {
```

2022-12-06 19:14 UTC, SergeiKuznetsov commented on src/test/java/tests/ABCTest.java
> +
```suggestion
```

2022-12-07 07:24 UTC, verafes approved these changes

2022-12-08 17:37 UTC, ArinaJur requested changes
С этим PR нужно разбираться отдельно. я не очень поняла смысл удаления методов, и идея теста не правильная (считывание expectedResult со страницы). Напишите мне, пожалуйста, когда вы сможете встретиться в zoom, мы пройдем по тесту.

2022-12-08 17:37 UTC, ArinaJur commented on src/test/java/pages/base_abstract/TablePage.java
> +        return getListText(letters);
А зачем у нас возникла необходимость менять начинку метода? Этот метод был предназначен для считывания текста и перевода его в нижний регистр. Для считывания текста as is у нас есть метод getListText()

У нас упадут тесты, которые были завязаны на методе getSubmenuLettersLowerCase() - или у нас не было таких тестов? Если не было и ваш первый, и вы хотите поменять начинку, то поменяйте, пожалуйста, и название метода, чтобы не путаться и не думать, что вернуться слова в lower case

2022-12-08 17:37 UTC, ArinaJur commented on src/test/java/pages/base_abstract/TablePage.java
> +    public List<String> getColumLanguageList(){
Если вы хотите метод, который специально переводит считанный текст в UpperCase, то этот метод должен называться getColumnsLanguageListInUpperCase() и можно создать отдельный метод, не удаляя метод для LowerCase. Не вижу необходимости удаления старого метода

2022-12-08 17:37 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +    public void test_ABCLetterCategoryLanguagesColumInformation() throws InterruptedException {
Уберите throws InterruptedException пожалуйста

2022-12-08 17:37 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +                 openBaseURL()
Здесь лишний пробел перед openBaseURL()

2022-12-08 17:37 UTC, ArinaJur commented on src/test/java/tests/ABCTest.java
> +        List<String> expectedLanguagesNames =
Для expectedResult мы должны просто создать лист и внести значения вручную. Мы не можем считывать со страницы ExpecteResult

2022-12-08 17:51 UTC, AramH20 commented on src/test/java/pages/base_abstract/TablePage.java
> +        return getListText(letters);
Здравствуйте Ирина. Спасибо за твою абзор будет здорово если сможете мне помочь. Я прямо сечас могу зайти в zoom

2022-12-09 21:32 UTC, ArinaJur approved these changes

2022-12-09 21:32 UTC, merged

2022-12-09 21:33 UTC, AramH20 commented
Thanks Irina ))