MariaKuzh
RedRoverSchool/AutomationQA_05 pull request #38
Opened 2022-11-14 04:02 UTC by MariaKuzh

testSearchForLanguageByName_HappyPath() added

2022-11-14 06:05 UTC, AnastasiaYY approved these changes

2022-11-14 06:05 UTC, AnastasiaYY commented on src/test/java/MariaKuzhTest.java
> +        searchLanguagesMenu.click();
добавьте здесь пробел, так как нужно разделение метлу действиями

2022-11-14 06:11 UTC, AnastasiaYY commented
Мария, посмотрите еще по лекции, как оформлять PR. Необходимо добавить ссылки на US, TC и AT.  А также нужно ветку правильно называть.

2022-11-14 19:03 UTC, ArinaJur requested changes
Пожалуйста, измените заголовок PR согласно правилам, так же добавьте ссылки на карточки Трелло в описание. Как в этом PR
![Screenshot_20221114_135832_Chrome](https://user-images.githubusercontent.com/66705803/201744060-d19e1473-7056-4c98-bf90-2bb00c438ffd.png)

2022-11-15 03:38 UTC, MariaKuzh commented on src/test/java/MariaKuzhTest.java
> +        searchLanguagesMenu.click();
Смогу ли поменять код, если я уже удалила свою ветку?

2022-11-15 03:55 UTC, ArinaJur approved these changes

2022-11-15 04:04 UTC, AnastasiaYY approved these changes

2022-11-15 04:05 UTC, AnastasiaYY commented on src/test/java/MariaKuzhTest.java
> +        searchLanguagesMenu.click();
можно со следующим PR сделать, если незначительные изменения типа пробелов

2022-11-15 04:40 UTC, merged