[AT] SearchForLanguageFieldByName_HappyPat<Tatyana-Belikova>
RedRoverSchool/AutomationQA_05 pull request #50
Opened 2022-11-15 09:30 UTC by Tatyana-Belikova

At search form search language field tatyana belikova

[US] - https://trello.com/c/f8JSGa4j/210-usfunctionalsearchform-search-for-language-field-tatyana-belikova
[TC] - https://trello.com/c/gA8SbQd0/264-tcsearchform-verify-if-user-is-searching-for-programming-languege-by-name-he-can-see-the-list-of-relative-resultstatyana-belikov
[AT] - https://trello.com/c/xx20gKt9/262-atsearchform-testsearchforlanguagefieldbynamehappypattatyana-belikova

2022-11-15 09:53 UTC, AndreiMironau requested changes
В карточке ТС, нет ссылок на US и АТ.
В карточке АТ (в шагах) включен код Assert. Шаги включают код до Assert. Исправьте пожалуйста.

2022-11-15 13:58 UTC, KseniyaKudrina approved these changes

2022-11-15 21:42 UTC, Tatyana-Belikova commented
Исправила. Карточка ТС содержит вложения, почему то они не отображаются.

2022-11-16 05:12 UTC, AndreiMironau approved these changes

2022-11-16 09:27 UTC, merged